# Generated by Django 4.1.1 on 2022-10-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_alter_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizusuario',
            name='usuario',
            field=models.IntegerField(verbose_name='Ip usuario'),
        ),
    ]
