# Generated by Django 4.1.1 on 2022-10-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_alter_quizusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizusuario',
            name='usuario',
            field=models.TextField(verbose_name='Ip usuario'),
        ),
    ]
