# Generated by Django 4.1.1 on 2022-10-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0020_pregunta_tipo_pregunta_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.TextField(verbose_name='Tipo de pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='unidad',
            field=models.IntegerField(verbose_name='Unidad a la que pertenece'),
        ),
    ]
