# Generated by Django 4.1.1 on 2022-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0021_alter_pregunta_tipo_alter_pregunta_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizusuario',
            name='nombre',
            field=models.TextField(null=True, verbose_name='Nombre del usuario'),
        ),
    ]
