# Generated by Django 4.1.1 on 2022-11-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0023_preguntasrespondidas_nombreuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='dificultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dificultad', to='Quiz.pregunta'),
        ),
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='uso_ayuda',
            field=models.BooleanField(default=False, verbose_name='¿Utilizo ayuda?'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texto_pregunta', to='Quiz.pregunta'),
        ),
    ]
