# Generated by Django 4.1.1 on 2022-11-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0024_preguntasrespondidas_dificultad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('nombreUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario_username', to='Quiz.quizusuario')),
                ('quizUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='Quiz.quizusuario')),
            ],
        ),
    ]
