# Generated by Django 4.1.1 on 2022-11-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0025_comentariousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='dificultad',
            field=models.IntegerField(null=True, verbose_name='Dificultad de la pregunta'),
        ),
    ]
