# Generated by Django 4.1.1 on 2022-11-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0026_alter_preguntasrespondidas_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='tiempo_pregunta',
            field=models.IntegerField(null=True, verbose_name='Tiempo que de la pregunta'),
        ),
    ]
